### ISSUE TITLE
Interface methods return itself or another interface

### ISSUE THREAD

**Issue by drumsta** [butuzov/ireturn#91] opened 2024-04-04 10:50 UTC
How to deal with the case below?

```
// Bad.
type Doer interface { Do() Doer }
type IDoer struct{}
func New() Doer { return new(IDoer)}
func (d *IDoer) Do() Doer {/*...*/ return d }

// Good.
type Doer interface { Do() Doer }
type IDoer struct{}
func New() *IDoer { return new(IDoer)}
func (d *IDoer) Do() *IDoer {/*...*/ return d}

// Very Good (Verify Interface Compliance in compile time)
var _ Doer = (*IDoer)(nil)
```

The above won't compile because of the error:

```
cannot use (*IDoer)(nil) (value of type *IDoer) as Doer value in variable declaration: *IDoer does not implement Doer (wrong type for method Do)
		have Do() *IDoer
		want Do() Doer
```

This use case is quite common designing libraries. As an example, standard slog package has this interface, that's Handler methods return the Handler interface.

```
type Handler interface {
	Enabled(context.Context, Level) bool
	WithAttrs(attrs []Attr) Handler
	WithGroup(name string) Handler
}
```

**Comment by butuzov** [comment] 2024-04-13 05:28
closed as duplicate of https://github.com/butuzov/ireturn/issues/21

**Closed by butuzov** 2024-04-13 05:28 UTC
